# Generated by Django 6.0 on 2025-12-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_event_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoussession',
            name='display_name',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
