# Generated by Django 6.0 on 2025-12-15 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_anonymoussession_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclinktoken',
            name='anonymous_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.anonymoussession'),
        ),
    ]
