# Generated by Django 6.0 on 2025-12-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_eventfeature_eventmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_covers/'),
        ),
        migrations.AddField(
            model_name='event',
            name='menu_file',
            field=models.FileField(blank=True, null=True, upload_to='event_menus/'),
        ),
    ]
